language: elixir
elixir:
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.2.4
  - 1.2.5
  - 1.2.6
  - 1.3.0
  - 1.3.1
otp_release:
  - 17.5
  - 18.3
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.2.6
    - otp_release: 19.0
      elixir: 1.3.0
    - otp_release: 19.0
      elixir: 1.3.1
